name: CI from shared workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason: 
        description: "Reason for running workflow manually"
        required: true

jobs:
  build:
    uses: SolidifyDemo/shared-templates/.github/workflows/common-build.yml@7ce717f311b5c6f4f6705f7c333c3ddf014898e5
    with:
      configuration: "Release"
