name: CI-CD workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason: 
        description: "Reason for running workflow manually"
        required: true

jobs:
  build:

    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package
      run: dotnet publish -c Release -o webapp
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: webapp
        path: webapp/**

  deploy_dev:
    name: "Deploy to the dev environment"
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: testing workflow
        run: echo ${{ secrets.AZURE_CREDENTIALS }}
      
  deploy_staging:
    name: "Deploy to the staging environment"
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - name: testing workflow
        run: echo ${{ secrets.AZURE_CREDENTIALS }}
    
    
